apiVersion: apps/v1
kind: Deployment
metadata:
  name: port-kube-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: port-kube
  template:
    metadata:
      labels:
        app: port-kube
    spec:
      containers:
      - name: port-kube
        image: ajansharma7/port-kube:latest
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: port-kube-service
spec:
  selector:
    app: port-kube
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
